### PR TITLE
change sbt image to openjdk

### PR DESCRIPTION
**Pull request by jstriebel**
This changes the sbt image to use openjdk, based on debian

### CODE REVIEW

**Comment by jstriebel** [comment]
@normanrz, should we split into `sbt` and `wk-dev` image, or just rename to `wk-dev`.

**Comment by normanrz** [comment]
Yeah we should split and put the `wk-dev` as `Dockerfile.dev` in the webknossos repo.

**Comment by jstriebel** [comment]
@normanrz node & yarn belong then to the wk `Dockerfile.dev`, right?

**Comment by normanrz** [comment]
arguably also postgres tools

**Pull request merged**
