### PR TITLE
inject utm_source=wklink in wklink redirects

### PR DESCRIPTION
**Pull request by normanrz**
Adding the `utm_source=wklink` param to the redirect URL, we should be able to detect wklink referrals in Google Analytics which would be very insightful.

### CODE REVIEW

**Review by jstriebel — APPROVED** [review]
LGTM :+1:

**Comment by normanrz** [comment]
@jstriebel Do you still have the microbadger keys somewhere? I can't extract them from CircleCI.

**Comment by jstriebel** [comment]
@jstriebel Do you still have the microbadger hooks somewhere? I can't extract them from CircleCI.

Nope, I'll simply remove it. From their website:

> We're sad to announce that microbadger.com will shutdown on 1st July 2021

**Comment by normanrz** [comment]
Alright. Done in https://github.com/scalableminds/dockerfiles/commit/d62037bfe9b0c3caa484ff7ff4543219f3060528

**Pull request merged**
